import Head from 'next/head';
import ProfileDetailCard from '@/components/marketplace/profile/ProfileDetailCard';
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import Typography from '@mui/material/Typography';
import { useMemo } from 'react';
import { useTheme } from '@mui/material/styles';
import { useQuery } from 'react-query';
import fetchCompany from '@/middlewares/fetchCompany';
import { useRouter } from 'next/router';
import ListingCard from '@/components/ListingCard';
import { useSession } from 'next-auth/react';

const useGetUser = (userUuid: string) => {
  const { data } = useQuery('userData', async () => fetchCompany(userUuid), {
    enabled: userUuid !== undefined,
  });
  return data;
};

// function to seperate string based on -
const splitString = (str: string) => str.split('-');

const ShareFunctionPage = () => {
  const router = useRouter();
  const loggedUserUuid = useSession().data?.user.id as string;
  const userDetails = useGetUser(loggedUserUuid);
  let listingIds;
  if (userDetails) {
    console.log(userDetails);
  }

  if (router.query.id) {
    listingIds = splitString(router.query.id as string);
  }
  return (
    <>
      <Head>
        <title>Share Function</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box sx={{ display: 'flex' }}>
          {userDetails && <ProfileDetailCard data={userDetails} visibleEditButton />}

          {/* map listing cards based on listing Ids */}
          {listingIds?.map((id) => (
            <ListingCard key={id} listingId={id} />
          ))}
        </Box>
      </main>
    </>
  );
};

export default ShareFunctionPage;
