import Head from 'next/head';
import { Button } from '@inc/ui';

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button onClick={() => console.log('clicked')}>Hello</Button>
        <p>Hello World</p>
      </main>
    </>
  );
};

export default Home;
