// ** React Imports
import { useMemo } from 'react';

// ** Next Imports
import Head from 'next/head';
import { useRouter } from 'next/router';

// ** MUI Imports
import Box from '@mui/material/Box';

// ** Custom Components Imports
import ProfileDetailCard from '@/components/marketplace/profile/ProfileDetailCard';

// ** HooksImports
import { useTheme } from '@mui/material/styles';
import { useQuery } from 'react-query';
import { useResponsiveness } from '@inc/ui';
import fetchCompany from '@/services/fetchCompany';

const useGetUser = (userUuid: string) => {
  console.log({ userUuid });
  const { data } = useQuery('userdata', async () => fetchCompany(userUuid), {
    enabled: userUuid !== undefined,
  });
  return data;
};

const ProfilePage = () => {
  const id = useRouter().query.id as string;
  console.log(id);
  const userDetails = useGetUser(id);

  const theme = useTheme();
  const { spacing } = theme;
  const [isSm, isMd, isLg] = useResponsiveness(['sm', 'md', 'lg']);

  const spaceStyle = useMemo(() => {
    if (isSm) {
      return {
        py: spacing(3),
        px: '20px',
        height: '100%;',
        width: '100%',
      };
    }
    if (isMd) {
      return {
        py: spacing(3),
        px: '40px',
        height: '100%;',
        width: '100%',
      };
    }
    if (isLg) {
      return {
        py: spacing(3),
        px: '60px',
        height: '100%;',
        width: '100%',
        display: 'flex',
        justifyContent: 'space-between',
      };
    }
    return {
      py: spacing(3),
      px: '20px',
      height: '100%;',
      width: '100%',
    };
  }, [isSm, isMd, isLg]);

  return (
    <>
      <Head>
        <title>{userDetails?.name}&lsquo;s Listings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box sx={spaceStyle}>
          {userDetails && <ProfileDetailCard data={userDetails} visibleEditButton />}
          <Box
            sx={{
              width: isLg ? '73%' : '100%',
              height: 'full',
              bgcolor: theme.palette.common.white,
              borderRadius: theme.shape,
              overflow: 'hidden',
            }}
          >
            {/* nth here */}
          </Box>
        </Box>
      </main>
    </>
  );
};

export default ProfilePage;
