import Head from 'next/head';
import ProfileDetailCard from '@/components/marketplace/profile/ProfileDetailCard';
import ListingsTab from '@/components/marketplace/profilePage/ListingsTab';
import ReviewsTab from '@/components/marketplace/profilePage/ReviewsTab';
import TabPanel from '@/components/marketplace/profilePage/TabPanel';
import Tabs from '@mui/material/Tabs';
import Tab from '@mui/material/Tab';
import SwipeableViews from 'react-swipeable-views';
import Box from '@mui/material/Box';
import { useState, SyntheticEvent, useMemo } from 'react';
import { useTheme, styled } from '@mui/material/styles';
import { useQuery } from 'react-query';
import fetchCompany from '@/middlewares/fetchCompany';
import { useRouter } from 'next/router';
import { useResponsiveness } from '@inc/ui';
import { useTranslation } from 'react-i18next';

const StyledTab = styled(Tab)(({ theme }) => ({
  minHeight: 60,
  bgcolor: theme.palette.common.white,
  color: theme.palette.primary[400],
  border: 1,
  borderColor: theme.palette.primary[400],
  borderRadius: theme.shape.borderRadius,
  //   for some reason, half of this doesn't work??
  //   upon further investigation seems like it's more specifically the ones regarding border, including the styles above
  '&.Mui-selected': {
    minHeight: 60,
    color: theme.palette.common.white,
    bgcolor: theme.palette.primary[400],
    border: 1,
    borderColor: theme.palette.primary[400],
    borderRadius: theme.shape,
  },
}));

const useGetUser = (userUuid: string) => {
  const { data } = useQuery('userdata', async () => fetchCompany(userUuid), {
    enabled: userUuid !== undefined,
  });
  return data;
};

const ProfilePage = () => {
  const id = useRouter().query.id as string;
  const userDetails = useGetUser(id);
  const { t } = useTranslation();

  const theme = useTheme();
  const { spacing } = theme;
  const [value, setValue] = useState(0);
  const [isSm, isMd, isLg] = useResponsiveness(['sm', 'md', 'lg']);

  const handleChange = (event: SyntheticEvent, newValue: number) => {
    setValue(newValue);
  };

  const handleChangeIndex = (index: number) => {
    setValue(index);
  };

  const spaceStyle = useMemo(() => {
    if (isSm) {
      return {
        py: spacing(3),
        px: '20px',
        height: '100%;',
        width: '100%',
      };
    }
    if (isMd) {
      return {
        py: spacing(3),
        px: '40px',
        height: '100%;',
        width: '100%',
      };
    }
    if (isLg) {
      return {
        py: spacing(3),
        px: '60px',
        height: '100%;',
        width: '100%',
        display: 'flex',
        justifyContent: 'space-between',
      };
    }
    return {
      py: spacing(3),
      px: '20px',
      height: '100%;',
      width: '100%',
    };
  }, [isSm, isMd, isLg]);

  return (
    <>
      <Head>
        <title>{userDetails?.name}&lsquo;s Listings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box sx={spaceStyle}>
          {userDetails && (
            <ProfileDetailCard data={userDetails} visibleEditButton />
          )}
          <Box
            sx={{
              width: isLg ? '73%' : '100%',
              height: 'full',
              bgcolor: theme.palette.common.white,
              borderRadius: theme.shape,
              overflow: 'hidden',
            }}
          >
            <Tabs
              value={value}
              onChange={handleChange}
              variant="fullWidth"
              sx={{
                '& .MuiTabs-indicator': {
                  display: 'none',
                },
              }}
            >
              <StyledTab
                label={t('Listings')}
                sx={{
                  // added in-line styling here because styled() doesn't want to work
                  border: 1,
                  borderColor: theme.palette.primary[400],
                  '&.Mui-selected': {
                    minHeight: 60,
                    color: theme.palette.common.white,
                    bgcolor: theme.palette.primary[400],
                    border: 1,
                    borderColor: theme.palette.primary[400],
                    borderRadius: theme.shape,
                  },
                }}
              />
              <StyledTab
                label={t('Reviews')}
                sx={{
                  border: 1,
                  borderColor: theme.palette.primary[400],
                  '&.Mui-selected': {
                    minHeight: 60,
                    color: theme.palette.common.white,
                    bgcolor: theme.palette.primary[400],
                    border: 1,
                    borderColor: theme.palette.primary[400],
                    borderRadius: theme.shape,
                  },
                }}
              />
            </Tabs>
            <SwipeableViews index={value} onChangeIndex={handleChangeIndex}>
              <TabPanel value={value} index={0} dir={theme.direction} height="100vh">
                <ListingsTab/>
              </TabPanel>
              <TabPanel value={value} index={1} dir={theme.direction} height="100vh">
                <ReviewsTab/>
              </TabPanel>
            </SwipeableViews>
          </Box>
        </Box>
      </main>
    </>
  );
};

export default ProfilePage;
