import Head from 'next/head';
import { Button } from '@inc/ui';
import type { Person } from '@inc/types';
import NavBar from '@/components/marketplace/navbar/NavBar';
import { signIn, useSession } from 'next-auth/react';
import S3Image from '@/components/S3Image';

// eslint-disable-next-line no-unused-vars
const p: Person = {
  id: 5,
  name: 'string',
};

const Home = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button onClick={() => console.log('clicked')}>Hello</Button>
        <p>Hello World</p>
        Not signed in <br />
        <button onClick={() => signIn()}>Sign in</button>
        <S3Image src="dcf658ac4b90e40a7e8c4cee75da2e17ce03c47a5058b867c3d65ac0adea3a41.gif" alt="randomImage"/>
      </main>

    </>
  );
};

// Home.includeNavbar = false;

export default Home;
