import Head from 'next/head';
import { useState } from 'react';
import { useRouter } from 'next/router';
import TransitionsModal from './modal';

const Home = () => {
  const [open, setOpen] = useState(false);
  const [leftButtonState, setLeftButtonState] = useState(false);
  const [rightButtonState, setRightButtonState] = useState(false);
  const handleOpen = () => setOpen(true);
  const router = useRouter();

  if (leftButtonState === true) {
    router.back();
  }

  const style = {
    backgroundColor: '#00C853',
    variant: 'contained',
    color: 'white'
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TransitionsModal
          modalButtonName="Open"
          modalButtonStyle={style}
          modalType="info"
          title="Confirmation"
          content="Once you leave the page, your changes will not be saved."
          leftButtonText="Stay here"
          rightButtonText="Leave page"
          leftButtonState={leftButtonState}
          rightButtonState={rightButtonState}
          setLeftButtonState={setLeftButtonState}
          setRightButtonState={setRightButtonState}
        />
      </main>
    </>
  );
};

export default Home;
