import Head from 'next/head';
// import { useState } from 'react';
import { useRouter } from 'next/router';
import React from 'react';
import TransitionsModal from '@inc/ui/lib/components/modal';
import ModalSelect from '@inc/ui/lib/components/modalSelect';

const Home = () => {
  const [open, setOpen] = React.useState(false);
  const [leftButtonState, setLeftButtonState] = React.useState(false);
  const [rightButtonState, setRightButtonState] = React.useState(false);
  const [selectInput, setSelectInput] = React.useState('');
  const handleOpen = () => setOpen(true);
  const router = useRouter();

  if (leftButtonState === true) {
    router.back();
  }

  const style = {
    backgroundColor: '#00C853',
    variant: 'contained',
    color: 'white',
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TransitionsModal
          modalButtonName="Open"
          modalButtonStyle={style}
          modalType="info"
          title="Confirmation"
          content="Once you leave the page, your changes will not be saved."
          leftButtonText={null} // <= only one button set as null
          rightButtonText="Stay here"
          leftButtonState={false} // <= only one button, set as false
          rightButtonState={rightButtonState}
          setLeftButtonState={setRightButtonState} // <= only one button, set as the rightButtonState
          setRightButtonState={setRightButtonState}
        />
        <ModalSelect
          modalButtonName="Open"
          modalButtonStyle={style}
          modalType="info"
          title="Make an offer"
          content="Enter an alternative amount to offer for the listing below."
          leftButtonText="cancel" // <= only one button set as null
          rightButtonText="make offer"
          selectInput={selectInput}
          setselectInput={setSelectInput}
          leftButtonState={false} // <= only one button, set as false
          rightButtonState={rightButtonState}
          setLeftButtonState={setRightButtonState} // <= only one button, set as the rightButtonState
          setRightButtonState={setRightButtonState}
        />
      </main>
    </>
  );
};

export default Home;
