name: Lint - Test - Build

# Skip job run if PR updated
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches: [main, dev]

jobs:
  lint:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS, pnpm and installs packages
        uses: ./.github/actions/setup

      - name: Build only @inc/ui
        run: pnpm build:ui

      - name: Lint
        run: pnpm lint

  # TODO: write this after the tests have been written
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup NodeJS, pnpm and installs packages
  #       uses: ./.github/actions/setup

  #     - name: Test
  #       run: pnpm test

  build:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS, pnpm and installs packages
        uses: ./.github/actions/setup

      - name: Create .env for prisma
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          directory: 'packages/db'
          file_name: .env
          fail_on_empty: true

      - name: Create .env.local for marketplace
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          envkey_NEXTAUTH_URL: http://localhost:3000
          envkey_NEXT_BUILD_OPTION: ignoreType
          envkey_NEXT_ESLINT_OPTION: ignoreLint
          directory: 'apps/marketplace'
          file_name: .env.local
          fail_on_empty: true

      - name: Build
        id: build-id
        run: pnpm build

      - name: Save @inc/ui dist build
        if: ${{ steps.build-id.outcome == 'success' }}
        uses: actions/upload-artifact@v3
        with:
          name: ui-dist
          path: packages/ui/dist

      - name: Save @inc/marketplace .next build
        if: ${{ steps.build-id.outcome == 'success' }}
        uses: actions/upload-artifact@v3
        with:
          name: marketplace-next
          path: apps/marketplace/.next
