name: Lint - Test - Build

# Skip job run if PR updated
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches: [main, dev]

jobs:
  lint:
    if: |
      startsWith(github.head_ref, 'feat') ||
      startsWith(github.head_ref, 'fix')
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS, pnpm and installs packages
        uses: ./.github/actions/setup

      - name: Build packages
        run: pnpm build:packages

      - name: Lint
        run: pnpm lint

  # TODO: write this after the tests have been written
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup NodeJS, pnpm and installs packages
  #       uses: ./.github/actions/setup

  #     - name: Test
  #       run: pnpm test

  build:
    if: |
      startsWith(github.head_ref, 'feat') ||
      startsWith(github.head_ref, 'fix')
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS, pnpm and installs packages
        uses: ./.github/actions/setup

      - name: Create .env for prisma
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          directory: 'packages/db'
          file_name: .env
          fail_on_empty: true

      - name: Create .env.local for marketplace
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          envkey_NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          envkey_NEXT_BUILD_OPTION: ${{ vars.NEXT_BUILD_OPTION }}
          envkey_NEXT_ESLINT_OPTION: ${{ vars.NEXT_ESLINT_OPTION }}
          directory: 'apps/marketplace'
          file_name: .env.local
          fail_on_empty: true

      - name: Build
        id: build-id
        run: pnpm build

      # - name: Save @inc/ui dist build
      #   if: ${{ steps.build-id.outcome == 'success' }}
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ui-dist
      #     path: packages/ui/dist

      # - name: Save @inc/events build
      #   if: ${{ steps.build-id.outcome == 'success' }}
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: events-build
      #     path: |
      #       packages/events/index.d.ts
      #       packages/events/index.js

      # - name: Save @inc/s3-simplified dist build
      #   if: ${{ steps.build-id.outcome == 'success' }}
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: s3-simplified-dist
      #     path: packages/s3-simplified/dist

      # - name: Save @inc/errors dist build
      #   if: ${{ steps.build-id.outcome == 'success' }}
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: errors-dist
      #     path: packages/errors/dist

      # - name: Save @inc/marketplace .next build
      #   if: ${{ steps.build-id.outcome == 'success' }}
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: marketplace-next
      #     path: apps/marketplace/.next

      # - name: Save @inc/chat dist build
      #   if: ${{ steps.build-id.outcome == 'success' }}
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: chat-dist
      #     path: apps/chat/dist
