name: Lint - Test - Build

# Skip job run if PR updated
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches: [main, dev]

jobs:
  lint:
    if: |
      startsWith(github.head_ref, 'feat') ||
      startsWith(github.head_ref, 'fix')
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS, pnpm and installs packages
        uses: ./.github/actions/setup

      - name: Build packages
        run: pnpm build:packages

      - name: Lint
        run: pnpm lint

  # TODO: write this after the tests have been written
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup NodeJS, pnpm and installs packages
  #       uses: ./.github/actions/setup

  #     - name: Test
  #       run: pnpm test

  build:
    if: |
      startsWith(github.head_ref, 'feat') ||
      startsWith(github.head_ref, 'fix')
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS, pnpm and installs packages
        uses: ./.github/actions/setup

      - name: Create .env for prisma
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          directory: 'packages/db'
          file_name: .env
          fail_on_empty: true

      - name: Create .env.local for marketplace
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          envkey_NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          envkey_NEXT_BUILD_OPTION: ${{ vars.NEXT_BUILD_OPTION }}
          envkey_NEXT_ESLINT_OPTION: ${{ vars.NEXT_ESLINT_OPTION }}
          envkey_MEILI_MASTER_KEY: ${{ secrets.MEILI_MASTER_KEY }}
          envkey_NEXT_PUBLIC_MEILI_MASTER_KEY: ${{ secrets.MEILI_MASTER_KEY }}
          envkey_MEILI_URL: ${{ secrets.MEILI_URL }}
          envkey_NEXT_PUBLIC_MEILI_URL: ${{ secrets.MEILI_URL }}
          directory: 'apps/marketplace'
          file_name: .env.local
          fail_on_empty: true

      - name: Create .env.local for admin
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          envkey_NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          envkey_NEXT_BUILD_OPTION: ${{ vars.NEXT_BUILD_OPTION }}
          envkey_NEXT_ESLINT_OPTION: ${{ vars.NEXT_ESLINT_OPTION }}
          directory: 'apps/admin'
          file_name: .env.local
          fail_on_empty: true

      - name: Replace eslint config files
        run: |
          rm -rf ./apps/marketplace/.eslintrc.json ./apps/admin/.eslintrc.json
          cp ./apps/marketplace/.eslintrc.cli.json ./apps/marketplace/.eslintrc.json
          cp ./apps/admin/.eslintrc.cli.json ./apps/admin/.eslintrc.json

      - name: Build
        id: build-id
        run: pnpm build
