name: Production Preview Deployment to AWS

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [dev]

jobs:
  preview-marketplace:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and save docker images
        id: save-docker-image
        run: |
          docker build -t ${{ secrets.AWS_REPOSITORY_URI }}/marketplace:latest -f apps/marketplace/Dockerfile --build-arg DATABASE_URL="${{ secrets.DATABASE_URL }}" --build-arg NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" --build-arg NEXTAUTH_URL="http://ec2-18-142-177-240.ap-southeast-1.compute.amazonaws.com" .
          docker build -t ${{ secrets.AWS_REPOSITORY_URI }}/marketplace:${{ github.sha }} -f apps/marketplace/Dockerfile --build-arg DATABASE_URL="${{ secrets.DATABASE_URL }}" --build-arg NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" --build-arg NEXTAUTH_URL="http://ec2-18-142-177-240.ap-southeast-1.compute.amazonaws.com" .
        # docker save ${{ secrets.AWS_REPOSITORY_URI }}/marketplace:${{ github.sha }} > marketplace-${{ github.sha }}.tar

      # - uses: actions/upload-artifact@v3
      #   if: ${{ steps.save-docker-image.outcome == 'success' }}
      #   with:
      #     name: marketplace-${{ github.sha }}.tar
      #     path: marketplace-${{ github.sha }}.tar
      #     retention-days: 1

      - name: Push images into ECR
        run: |
          docker push ${{ secrets.AWS_REPOSITORY_URI }}/marketplace:${{ github.sha }}
          docker push ${{ secrets.AWS_REPOSITORY_URI }}/marketplace:latest

      - name: Restart task
        # TODO: do not restart tasks like this
        run: aws ecs update-service --force-new-deployment --service marketplace-service --cluster marketplace

      # instead, define a new task definition and update the service with the new task definition
      # but it will do for now :p

      - name: Get Public DNS and IP
        run: |
          echo "public_dns_name=$(aws ec2 describe-instances --instance-ids i-0a8375b1fe54c7fb3 --query 'Reservations[].Instances[].PublicDnsName' --output text)" >> "$GITHUB_ENV"
          echo "public_ip_address=$(aws ec2 describe-instances --instance-ids i-0a8375b1fe54c7fb3 --query 'Reservations[].Instances[].PublicIpAddress' --output text)" >> "$GITHUB_ENV"
          echo "Public DNS: ${{ env.public_dns_name }}"
          echo "Public IP: ${{ env.public_ip_address }}"
